# All lengths are in millimetres
objects:
  ballRadius: 20

pitch:
  main:
    size: [1200, 690]
    corners: [80, 180]
    goalHeight: 300

    videoFrameProjection:
      centerPx: [315, 220]
      widthPx: 525

  side:
    size: [1200, 690]
    corners: [80, 180]
    goalHeight: 300

    videoFrameProjection:
      centerPx: [315, 220]
      widthPx: 525